CREATE TABLE IF NOT EXISTS companies (
	businessid TEXT NOT NULL,
	name TEXT NOT NULL,
	address TEXT NOT NULL,
	phone TEXT NOT NULL,
	website TEXT NOT NULL,
	saved TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);
